-- ████╗   ██╗   ██████╗   ██████╗  ██████╗ ██╗  ██╗ ██████╗ ██╗     █████╗  ██████╗  ██████╗ ██████╗    ██╗ --
-- ██╔██╗  ██║ ██╔═════╝   ██╔══██╗ ██╔═══╝ ██║  ██║ ██╔═══╝ ██║    ██╔══██╗ ██╔══██╗ ██╔═══╝ ██╔══██╗   ██║ --
-- ██║╚██╗ ██║ ██║         ██║  ██║ █████╗  ██║  ██║ █████╗  ██║    ██║  ██║ ██████╔╝ █████╗  ██████╔╝   ██║ --
-- ██║ ╚██╗██║ ██║         ██║  ██║ ██╔══╝  ╚██╗██╔╝ ██╔══╝  ██║    ██║  ██║ ██╔═══╝  ██╔══╝  ██╔══██╗   ╚═╝ --
-- ██║  ╚████║ ╚═██████╗   ██████╔╝ ██████╗  ╚███╔╝  ██████╗ ██████╗╚█████╔╝ ██║      ██████╗ ██║  ██║   ██╗ --
-- ╚═╝   ╚═══╝   ╚═════╝   ╚═════╝  ╚═════╝   ╚══╝   ╚═════╝ ╚═════╝ ╚════╝  ╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝ --

-- น้ำหนักของสิ่งของชนิดต่างๆต่อ 1 ชิ้น (หน่วยเป็น Kg) ** หากไม่ใส่ จะอิงตามน้ำหนักในระบบ es_extended หรือเบสอื่นๆ
Config.ItemsWeight = {
	-- ['bread'] = 500,
	-- ['water'] = 500,
}

-- Limit ของสิ่งของชนิดต่างๆ ** หากไม่ใส่ จะอิงตาม Limit ในระบบ es_extended หรือเบสอื่นๆ
Config.ItemsLimit = {
	-- ['bread'] = 5,
	-- ['water'] = 5,
}

-- ความหายากของสิ่งของชนิดต่างๆ ** หากไม่ใส่ จะอิงตาม Rarity ในระบบ es_extended หรือเบสอื่นๆ
Config.ItemsRarity = {
	-- ['bread'] = 1,
	-- ['water'] = 2,
}

-- ปิดกระเป๋าเมื่อใช้งานสิ่งของต่างๆ
Config.CloseInventoryOnUseItem = {
	'radio',
	'dpm_radio',
	'repairkit',
	'dpm_repaitkit',
	'water',
}

-- ปิดกระเป๋าเมื่อทิ้งสิ่งของต่างๆ
Config.CloseInventoryOnDropItem = {
	-- 'bread',
	-- 'water',
}

-- สิ่งของที่ต้องการให้เก็บอาวุธก่อนแล้วจึงใช้งาน
Config.PocketWeaponWhenUse = {
	-- 'bread',
	-- 'water',
}

-- Blacklist ทิ้งของ/มอบของ
Config.ItemsActionList = {
	shortcut = {				-- การ Item ของเข้า Shortcuts
		type = 'blacklist',		-- ชนิดของ List ที่ต้องการ (whitelist|blacklist)
		list = {
			-- 'bread',
			-- 'water',
		}
	},
	use = {						-- การ "ใช้" สิ่งของต่างๆ
		type = 'blacklist',
		list = {
			-- 'bread',
			-- 'water',
		}
	},
	drop = {					-- การ "ทิ้ง" สิ่งของต่างๆ
		type = 'blacklist',
		list = {
			'gacha_blackmoney',
			'gacha_economy',
			'gacha_evant',
			'gacha_money',
			'dpm_armor',
			'dpm_radio',
			'oxygen_mask',
			'box_newplayer',
			'boxcard_newplayer',


			--Fashion
			'wing_blade',
			'wing_godeye',
			'wing_wolfice',
			'wing_devileye',
			'wing_dragonhalf',
			'wing_celestial',
			'wing_chada',
			'wing_crystal',
			'281bagcatsl',
			'281bobcat',
			'281council1',
			'281council2',
			'281council3',
			'281council4',
			'281gatitoscat1',
			'281gatitoscat2',
			'281snowbirds',
			'281timsum',
			'bingsu_blue',
			'bingsu_coke',
			'bingsu_green',
			'bingsu_red',
			'bingsu_yellow',
			'bingsu_cokehead',
			'bingsu_greenhead',
			'bingsu_rainbow',
			'bingsu_redhead',
			'bingsu_yellowhead',
			'gudetama1',
			'gudetama2',
			'gudetama3',
			'gudetama4',
			'gudetama5',
			'gudetama6',
			'gudetama7',
			'gudetama8',
			'gudetama9',
			'gudetama10',
			'ufoxanim_head',
			'head_aline1',
			'head_aline2',
			'blueguncable_hand',
			'redguncable_hand',
			'jetpack_bag',
			'keepanawut1',
			'keepanawut2',
			'unicornsping1_head',
			'unicornsping2_head',
			'072air_baloon2tone',
			'072air_baloonbag',
			'072bear',
			'072bouquet',
			'072chocolate',
			'072heart',
			'beary_bag',
			'caty_bag',
			'unicorn_bag',
			'cap_cat',
			'icecream_pad_01',
			'icecream_pad_02',
			'icecream_pad_03',
			'crep_egg',
			'crep_hotdog',
			'crep_mixberry',
			'crep_straw',
			'bloo_shark',
			'catsudon',
			'cutebanana',
			'charmander',
			'cupcake',
			'cutebunnymech',
			'dinosaur',
			'slimeblack',
			'slimeblue',
			'slimegreen',
			'slimered',
			'chichan_head',
			'dijimon_bag',
			'dino_head',
			'doraemon_bag',
			'nees_bag',
			'plesiocute_bag',
			'selorcat_bag',
			'shinchan_bag',
			'shiro_head',
			'shoesdino_l',
			'shoesdino_r',
			'1502ace',
			'1502chopper',
			'1502law',
			'1502mihawk',
			'1502nami',
			'1502robin',
			'1502sanji',
			'1502shanks',
			'1502usopp',
			'1502zoro',
			'dunuts_bluepenut_bag',
			'dunuts_chocoice_bag',
			'dunuts_creamice_bag',
			'dunuts_darkpenut_bag',
			'dunuts_strawpenut_bag',
			'dunuts_teaice_bag',
			'dunuts_bluepenut',
			'dunuts_chocoice',
			'dunuts_creamice',
			'dunuts_darkpenut',
			'dunuts_strawpenut',
			'dunuts_teaice',
			'chonky_axolotl_head',
			'cute_duck_head',
			'kawaii_cats1_head',
			'kawaii_cats2_head',
			'kawaii_cats3_head',
			'parade_cats1',
			'parade_cats2',
			'parade_cats3',
			'parade_cats4',
			'sexycats1',
			'sexycats2',
			'sexycats3',
			'sexycats4',
			'1702arvawinged',
			'1702cakesweetbunny',
			'1702cat_foot_Left',
			'1702cat_foot_Right',
			'1702cat_Head',
			'1702iscream_Mouth',
			'1702kittyphone',
			'1702rainscarecrow_2arm',
			'1702seal_Head',
			'1702tail',
			'1702wingfire',
			'We_bear_01',
			'We_bear_02',
			'We_bear_03',
			'2702couragedog',
			'2702ghost',
			'2702gudetamasleepbag',
			'2702kevin',
			'2702omnom',
			'2702rabbit',
			'2702takodachi',
			'2702magalongcat',
			'daruma1_mask',
			'daruma2_mask',
			'duck1_hat',
			'duck2_hat',
			'fox1_mask',
			'fox2_mask',
			'moji1_mask',
			'moji2_mask',
			'pakpao1_mask',
			'pakpao2_mask',
			'boostdiscord',
			'new_player',
			'012bunny1',
			'012bunny2',
			'012bunny3',
			'012bunnydonuts',

			-- Item Work
			'stone',
			'red_gem',
			'pink_gem',
			'green_gem',
			'blue_gem',
			'grout',
			'iron_a',
			'iron_b',
			'pig',
			'whale',
			'lettuce',
			'tomato',
			'honey',
			'strawberry',
			'lobster',
			'pig',
			'egg',
			'squid',
			'wood',
			'salmon',
			'card_cow',
			'animal_food',
			'cow_milk',
			'cement',
			'cable',
			'scrap_cement',
			'scrap_cable',

		
		}
	},
	give = {					-- การ "มอบ" สิ่งของต่างๆ
		type = 'blacklist',
		list = {
			'gacha_blackmoney',
			'gacha_economy',
			'gacha_evant',
			'gacha_money',
			'dpm_armor',
			'dpm_radio',
			'oxygen_mask',
			'box_newplayer',
			'boxcard_newplayer',

			'wing_blade',
			'wing_godeye',
			'wing_wolfice',
			'wing_devileye',
			'wing_dragonhalf',
			'wing_celestial',
			'wing_chada',
			'wing_crystal',
			'281bagcatsl',
			'281bobcat',
			'281council1',
			'281council2',
			'281council3',
			'281council4',
			'281gatitoscat1',
			'281gatitoscat2',
			'281snowbirds',
			'281timsum',
			'bingsu_blue',
			'bingsu_coke',
			'bingsu_green',
			'bingsu_red',
			'bingsu_yellow',
			'bingsu_cokehead',
			'bingsu_greenhead',
			'bingsu_rainbow',
			'bingsu_redhead',
			'bingsu_yellowhead',
			'gudetama1',
			'gudetama2',
			'gudetama3',
			'gudetama4',
			'gudetama5',
			'gudetama6',
			'gudetama7',
			'gudetama8',
			'gudetama9',
			'gudetama10',
			'ufoxanim_head',
			'head_aline1',
			'head_aline2',
			'blueguncable_hand',
			'redguncable_hand',
			'jetpack_bag',
			'keepanawut1',
			'keepanawut2',
			'unicornsping1_head',
			'unicornsping2_head',
			'072air_baloon2tone',
			'072air_baloonbag',
			'072bear',
			'072bouquet',
			'072chocolate',
			'072heart',
			'beary_bag',
			'caty_bag',
			'unicorn_bag',
			'cap_cat',
			'icecream_pad_01',
			'icecream_pad_02',
			'icecream_pad_03',
			'crep_egg',
			'crep_hotdog',
			'crep_mixberry',
			'crep_straw',
			'bloo_shark',
			'catsudon',
			'cutebanana',
			'charmander',
			'cupcake',
			'cutebunnymech',
			'dinosaur',
			'slimeblack',
			'slimeblue',
			'slimegreen',
			'slimered',
			'chichan_head',
			'dijimon_bag',
			'dino_head',
			'doraemon_bag',
			'nees_bag',
			'plesiocute_bag',
			'selorcat_bag',
			'shinchan_bag',
			'shiro_head',
			'shoesdino_l',
			'shoesdino_r',
			'1502ace',
			'1502chopper',
			'1502law',
			'1502mihawk',
			'1502nami',
			'1502robin',
			'1502sanji',
			'1502shanks',
			'1502usopp',
			'1502zoro',
			'dunuts_bluepenut_bag',
			'dunuts_chocoice_bag',
			'dunuts_creamice_bag',
			'dunuts_darkpenut_bag',
			'dunuts_strawpenut_bag',
			'dunuts_teaice_bag',
			'dunuts_bluepenut',
			'dunuts_chocoice',
			'dunuts_creamice',
			'dunuts_darkpenut',
			'dunuts_strawpenut',
			'dunuts_teaice',
			'chonky_axolotl_head',
			'cute_duck_head',
			'kawaii_cats1_head',
			'kawaii_cats2_head',
			'kawaii_cats3_head',
			'parade_cats1',
			'parade_cats2',
			'parade_cats3',
			'parade_cats4',
			'sexycats1',
			'sexycats2',
			'sexycats3',
			'sexycats4',
			'1702arvawinged',
			'1702cakesweetbunny',
			'1702cat_foot_Left',
			'1702cat_foot_Right',
			'1702cat_Head',
			'1702iscream_Mouth',
			'1702kittyphone',
			'1702rainscarecrow_2arm',
			'1702seal_Head',
			'1702tail',
			'1702wingfire',
			'We_bear_01',
			'We_bear_02',
			'We_bear_03',
			'2702couragedog',
			'2702ghost',
			'2702gudetamasleepbag',
			'2702kevin',
			'2702omnom',
			'2702rabbit',
			'2702takodachi',
			'2702magalongcat',
			'daruma1_mask',
			'daruma2_mask',
			'duck1_hat',
			'duck2_hat',
			'fox1_mask',
			'fox2_mask',
			'moji1_mask',
			'moji2_mask',
			'pakpao1_mask',
			'pakpao2_mask',
			'boostdiscord',
			'new_player',
			'012bunny1',
			'012bunny2',
			'012bunny3',
			'012bunnydonuts',
		
		}
	},
	search = {					-- การ "โยกย้าย" สิ่งของต่างๆเมื่อเปิดกระเป๋าผู้เล่น
		type = 'blacklist',
		list = {
			-- 'gacha_blackmoney',
			-- 'gacha_economy',
			-- 'gacha_evant',
			-- 'gacha_money',
			-- 'dpm_armor',
			-- 'dpm_radio',
			-- 'oxygen_mask',
			-- 'box_newplayer',
			-- 'boxcard_newplayer',

			-- 'wing_blade',
			-- 'wing_godeye',
			-- 'wing_wolfice',
			-- 'wing_devileye',
			-- 'wing_dragonhalf',
			-- 'wing_celestial',
			-- 'wing_chada',
			-- 'wing_crystal',
			-- '281bagcatsl',
			-- '281bobcat',
			-- '281council1',
			-- '281council2',
			-- '281council3',
			-- '281council4',
			-- '281gatitoscat1',
			-- '281gatitoscat2',
			-- '281snowbirds',
			-- '281timsum',
			-- 'bingsu_blue',
			-- 'bingsu_coke',
			-- 'bingsu_green',
			-- 'bingsu_red',
			-- 'bingsu_yellow',
			-- 'bingsu_cokehead',
			-- 'bingsu_greenhead',
			-- 'bingsu_rainbow',
			-- 'bingsu_redhead',
			-- 'bingsu_yellowhead',
			-- 'gudetama1',
			-- 'gudetama2',
			-- 'gudetama3',
			-- 'gudetama4',
			-- 'gudetama5',
			-- 'gudetama6',
			-- 'gudetama7',
			-- 'gudetama8',
			-- 'gudetama9',
			-- 'gudetama10',
			-- 'ufoxanim_head',
			-- 'head_aline1',
			-- 'head_aline2',
			-- 'blueguncable_hand',
			-- 'redguncable_hand',
			-- 'jetpack_bag',
			-- 'keepanawut1',
			-- 'keepanawut2',
			-- 'unicornsping1_head',
			-- 'unicornsping2_head',
			-- '072air_baloon2tone',
			-- '072air_baloonbag',
			-- '072bear',
			-- '072bouquet',
			-- '072chocolate',
			-- '072heart',
			-- 'beary_bag',
			-- 'caty_bag',
			-- 'unicorn_bag',
			-- 'cap_cat',
			-- 'icecream_pad_01',
			-- 'icecream_pad_02',
			-- 'icecream_pad_03',
			-- 'crep_egg',
			-- 'crep_hotdog',
			-- 'crep_mixberry',
			-- 'crep_straw',
			-- 'bloo_shark',
			-- 'catsudon',
			-- 'cutebanana',
			-- 'charmander',
			-- 'cupcake',
			-- 'cutebunnymech',
			-- 'dinosaur',
			-- 'slimeblack',
			-- 'slimeblue',
			-- 'slimegreen',
			-- 'slimered',
			-- 'chichan_head',
			-- 'dijimon_bag',
			-- 'dino_head',
			-- 'doraemon_bag',
			-- 'nees_bag',
			-- 'plesiocute_bag',
			-- 'selorcat_bag',
			-- 'shinchan_bag',
			-- 'shiro_head',
			-- 'shoesdino_l',
			-- 'shoesdino_r',
			-- '1502ace',
			-- '1502chopper',
			-- '1502law',
			-- '1502mihawk',
			-- '1502nami',
			-- '1502robin',
			-- '1502sanji',
			-- '1502shanks',
			-- '1502usopp',
			-- '1502zoro',
			-- 'dunuts_bluepenut_bag',
			-- 'dunuts_chocoice_bag',
			-- 'dunuts_creamice_bag',
			-- 'dunuts_darkpenut_bag',
			-- 'dunuts_strawpenut_bag',
			-- 'dunuts_teaice_bag',
			-- 'dunuts_bluepenut',
			-- 'dunuts_chocoice',
			-- 'dunuts_creamice',
			-- 'dunuts_darkpenut',
			-- 'dunuts_strawpenut',
			-- 'dunuts_teaice',
			-- 'chonky_axolotl_head',
			-- 'cute_duck_head',
			-- 'kawaii_cats1_head',
			-- 'kawaii_cats2_head',
			-- 'kawaii_cats3_head',
			-- 'parade_cats1',
			-- 'parade_cats2',
			-- 'parade_cats3',
			-- 'parade_cats4',
			-- 'sexycats1',
			-- 'sexycats2',
			-- 'sexycats3',
			-- 'sexycats4',
			-- '1702arvawinged',
			-- '1702cakesweetbunny',
			-- '1702cat_foot_Left',
			-- '1702cat_foot_Right',
			-- '1702cat_Head',
			-- '1702iscream_Mouth',
			-- '1702kittyphone',
			-- '1702rainscarecrow_2arm',
			-- '1702seal_Head',
			-- '1702tail',
			-- '1702wingfire',
			-- 'We_bear_01',
			-- 'We_bear_02',
			-- 'We_bear_03',
			-- '2702couragedog',
			-- '2702ghost',
			-- '2702gudetamasleepbag',
			-- '2702kevin',
			-- '2702omnom',
			-- '2702rabbit',
			-- '2702takodachi',
			-- '2702magalongcat',
			-- 'daruma1_mask',
			-- 'daruma2_mask',
			-- 'duck1_hat',
			-- 'duck2_hat',
			-- 'fox1_mask',
			-- 'fox2_mask',
			-- 'moji1_mask',
			-- 'moji2_mask',
			-- 'pakpao1_mask',
			-- 'pakpao2_mask',
			-- 'boostdiscord',
			-- 'new_player',
			-- '012bunny1',
			-- '012bunny2',
			-- '012bunny3',
			-- '012bunnydonuts',
		}
	}
}
-- การตั้งค่า Action ต่างๆ
-- 'whitelist'	=> Items ต่างๆที่อยู่ใน List จะ "อนุญาต" ให้ทำการกระทำนั้นๆ
--				=> โดยที่ Items ที่ไม่อยู่ใน List จะ "ไม่อนุญาต" ให้ทำการกระทำนั้นๆ
-- 'blacklist'	=> Items ต่างๆที่อยู่ใน List จะ "ไม่อนุญาต" ให้ทำการกระทำนั้นๆ
--				=> โดยที่ Items ที่ไม่อยู่ใน List จะ "อนุญาต" ให้ทำการกระทำนั้นๆ